//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 關聯性中繼資料

[assembly: EdmRelationshipAttribute("pcsysModel", "FK_product_catogory", "catogory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(pc.Models.catogory), "product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(pc.Models.product), true)]
[assembly: EdmRelationshipAttribute("pcsysModel", "FK_order_member", "member", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(pc.Models.member), "order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(pc.Models.order), true)]
[assembly: EdmRelationshipAttribute("pcsysModel", "FK_orderDetail_order", "order", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(pc.Models.order), "orderDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(pc.Models.orderDetail), true)]

#endregion

namespace pc.Models
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class pcsysEntities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'pcsysEntities' 區段中找到的連接字串，初始化新的 pcsysEntities 物件。
        /// </summary>
        public pcsysEntities() : base("name=pcsysEntities", "pcsysEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 pcsysEntities 物件。
        /// </summary>
        public pcsysEntities(string connectionString) : base(connectionString, "pcsysEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 pcsysEntities 物件。
        /// </summary>
        public pcsysEntities(EntityConnection connection) : base(connection, "pcsysEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<catogory> catogory
        {
            get
            {
                if ((_catogory == null))
                {
                    _catogory = base.CreateObjectSet<catogory>("catogory");
                }
                return _catogory;
            }
        }
        private ObjectSet<catogory> _catogory;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<product> product
        {
            get
            {
                if ((_product == null))
                {
                    _product = base.CreateObjectSet<product>("product");
                }
                return _product;
            }
        }
        private ObjectSet<product> _product;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<member> member
        {
            get
            {
                if ((_member == null))
                {
                    _member = base.CreateObjectSet<member>("member");
                }
                return _member;
            }
        }
        private ObjectSet<member> _member;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<order> order
        {
            get
            {
                if ((_order == null))
                {
                    _order = base.CreateObjectSet<order>("order");
                }
                return _order;
            }
        }
        private ObjectSet<order> _order;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<orderDetail> orderDetail
        {
            get
            {
                if ((_orderDetail == null))
                {
                    _orderDetail = base.CreateObjectSet<orderDetail>("orderDetail");
                }
                return _orderDetail;
            }
        }
        private ObjectSet<orderDetail> _orderDetail;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 catogory EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTocatogory(catogory catogory)
        {
            base.AddObject("catogory", catogory);
        }
    
        /// <summary>
        /// 將新物件加入 product EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddToproduct(product product)
        {
            base.AddObject("product", product);
        }
    
        /// <summary>
        /// 將新物件加入 sysdiagrams EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// 將新物件加入 member EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTomember(member member)
        {
            base.AddObject("member", member);
        }
    
        /// <summary>
        /// 將新物件加入 order EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddToorder(order order)
        {
            base.AddObject("order", order);
        }
    
        /// <summary>
        /// 將新物件加入 orderDetail EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddToorderDetail(orderDetail orderDetail)
        {
            base.AddObject("orderDetail", orderDetail);
        }

        #endregion
    }
    

    #endregion
    
    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcsysModel", Name="catogory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class catogory : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 catogory 物件。
        /// </summary>
        /// <param name="id">id 屬性的初始值。</param>
        /// <param name="c_name">c_name 屬性的初始值。</param>
        public static catogory Createcatogory(global::System.Int32 id, global::System.String c_name)
        {
            catogory catogory = new catogory();
            catogory.id = id;
            catogory.c_name = c_name;
            return catogory;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String c_name
        {
            get
            {
                return _c_name;
            }
            set
            {
                Onc_nameChanging(value);
                ReportPropertyChanging("c_name");
                _c_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("c_name");
                Onc_nameChanged();
            }
        }
        private global::System.String _c_name;
        partial void Onc_nameChanging(global::System.String value);
        partial void Onc_nameChanged();

        #endregion
    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pcsysModel", "FK_product_catogory", "product")]
        public EntityCollection<product> product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<product>("pcsysModel.FK_product_catogory", "product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<product>("pcsysModel.FK_product_catogory", "product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcsysModel", Name="member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class member : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 member 物件。
        /// </summary>
        /// <param name="id">id 屬性的初始值。</param>
        /// <param name="username">username 屬性的初始值。</param>
        /// <param name="password">password 屬性的初始值。</param>
        /// <param name="name">name 屬性的初始值。</param>
        /// <param name="gender">gender 屬性的初始值。</param>
        /// <param name="birthday">birthday 屬性的初始值。</param>
        /// <param name="phone">phone 屬性的初始值。</param>
        /// <param name="address">address 屬性的初始值。</param>
        /// <param name="email">email 屬性的初始值。</param>
        /// <param name="role">role 屬性的初始值。</param>
        public static member Createmember(global::System.Int32 id, global::System.String username, global::System.String password, global::System.String name, global::System.String gender, global::System.DateTime birthday, global::System.String phone, global::System.String address, global::System.String email, global::System.Boolean role)
        {
            member member = new member();
            member.id = id;
            member.username = username;
            member.password = password;
            member.name = name;
            member.gender = gender;
            member.birthday = birthday;
            member.phone = phone;
            member.address = address;
            member.email = email;
            member.role = role;
            return member;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime birthday
        {
            get
            {
                return _birthday;
            }
            set
            {
                OnbirthdayChanging(value);
                ReportPropertyChanging("birthday");
                _birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("birthday");
                OnbirthdayChanged();
            }
        }
        private global::System.DateTime _birthday;
        partial void OnbirthdayChanging(global::System.DateTime value);
        partial void OnbirthdayChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String authcode
        {
            get
            {
                return _authcode;
            }
            set
            {
                OnauthcodeChanging(value);
                ReportPropertyChanging("authcode");
                _authcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("authcode");
                OnauthcodeChanged();
            }
        }
        private global::System.String _authcode;
        partial void OnauthcodeChanging(global::System.String value);
        partial void OnauthcodeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean role
        {
            get
            {
                return _role;
            }
            set
            {
                OnroleChanging(value);
                ReportPropertyChanging("role");
                _role = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("role");
                OnroleChanged();
            }
        }
        private global::System.Boolean _role;
        partial void OnroleChanging(global::System.Boolean value);
        partial void OnroleChanged();

        #endregion
    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pcsysModel", "FK_order_member", "order")]
        public EntityCollection<order> order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<order>("pcsysModel.FK_order_member", "order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<order>("pcsysModel.FK_order_member", "order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcsysModel", Name="order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class order : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 order 物件。
        /// </summary>
        /// <param name="id">id 屬性的初始值。</param>
        /// <param name="uid">uid 屬性的初始值。</param>
        /// <param name="receiver">receiver 屬性的初始值。</param>
        /// <param name="phone">phone 屬性的初始值。</param>
        /// <param name="address">address 屬性的初始值。</param>
        /// <param name="price">price 屬性的初始值。</param>
        /// <param name="payment">payment 屬性的初始值。</param>
        /// <param name="shipment">shipment 屬性的初始值。</param>
        public static order Createorder(global::System.Int32 id, global::System.Int32 uid, global::System.String receiver, global::System.String phone, global::System.String address, global::System.Decimal price, global::System.Boolean payment, global::System.Boolean shipment)
        {
            order order = new order();
            order.id = id;
            order.uid = uid;
            order.receiver = receiver;
            order.phone = phone;
            order.address = address;
            order.price = price;
            order.payment = payment;
            order.shipment = shipment;
            return order;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 uid
        {
            get
            {
                return _uid;
            }
            set
            {
                OnuidChanging(value);
                ReportPropertyChanging("uid");
                _uid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uid");
                OnuidChanged();
            }
        }
        private global::System.Int32 _uid;
        partial void OnuidChanging(global::System.Int32 value);
        partial void OnuidChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String receiver
        {
            get
            {
                return _receiver;
            }
            set
            {
                OnreceiverChanging(value);
                ReportPropertyChanging("receiver");
                _receiver = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("receiver");
                OnreceiverChanged();
            }
        }
        private global::System.String _receiver;
        partial void OnreceiverChanging(global::System.String value);
        partial void OnreceiverChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean payment
        {
            get
            {
                return _payment;
            }
            set
            {
                OnpaymentChanging(value);
                ReportPropertyChanging("payment");
                _payment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("payment");
                OnpaymentChanged();
            }
        }
        private global::System.Boolean _payment;
        partial void OnpaymentChanging(global::System.Boolean value);
        partial void OnpaymentChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean shipment
        {
            get
            {
                return _shipment;
            }
            set
            {
                OnshipmentChanging(value);
                ReportPropertyChanging("shipment");
                _shipment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("shipment");
                OnshipmentChanged();
            }
        }
        private global::System.Boolean _shipment;
        partial void OnshipmentChanging(global::System.Boolean value);
        partial void OnshipmentChanged();

        #endregion
    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pcsysModel", "FK_order_member", "member")]
        public member member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("pcsysModel.FK_order_member", "member").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("pcsysModel.FK_order_member", "member").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<member> memberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("pcsysModel.FK_order_member", "member");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<member>("pcsysModel.FK_order_member", "member", value);
                }
            }
        }
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pcsysModel", "FK_orderDetail_order", "orderDetail")]
        public EntityCollection<orderDetail> orderDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<orderDetail>("pcsysModel.FK_orderDetail_order", "orderDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<orderDetail>("pcsysModel.FK_orderDetail_order", "orderDetail", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcsysModel", Name="orderDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class orderDetail : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 orderDetail 物件。
        /// </summary>
        /// <param name="id">id 屬性的初始值。</param>
        /// <param name="orderId">orderId 屬性的初始值。</param>
        /// <param name="name">name 屬性的初始值。</param>
        /// <param name="amount">amount 屬性的初始值。</param>
        /// <param name="price">price 屬性的初始值。</param>
        public static orderDetail CreateorderDetail(global::System.Int32 id, global::System.Int32 orderId, global::System.String name, global::System.Int32 amount, global::System.Int32 price)
        {
            orderDetail orderDetail = new orderDetail();
            orderDetail.id = id;
            orderDetail.orderId = orderId;
            orderDetail.name = name;
            orderDetail.amount = amount;
            orderDetail.price = price;
            return orderDetail;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderId
        {
            get
            {
                return _orderId;
            }
            set
            {
                OnorderIdChanging(value);
                ReportPropertyChanging("orderId");
                _orderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderId");
                OnorderIdChanged();
            }
        }
        private global::System.Int32 _orderId;
        partial void OnorderIdChanging(global::System.Int32 value);
        partial void OnorderIdChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 amount
        {
            get
            {
                return _amount;
            }
            set
            {
                OnamountChanging(value);
                ReportPropertyChanging("amount");
                _amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("amount");
                OnamountChanged();
            }
        }
        private global::System.Int32 _amount;
        partial void OnamountChanging(global::System.Int32 value);
        partial void OnamountChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Int32 _price;
        partial void OnpriceChanging(global::System.Int32 value);
        partial void OnpriceChanged();

        #endregion
    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pcsysModel", "FK_orderDetail_order", "order")]
        public order order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<order>("pcsysModel.FK_orderDetail_order", "order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<order>("pcsysModel.FK_orderDetail_order", "order").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<order> orderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<order>("pcsysModel.FK_orderDetail_order", "order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<order>("pcsysModel.FK_orderDetail_order", "order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcsysModel", Name="product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class product : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 product 物件。
        /// </summary>
        /// <param name="id">id 屬性的初始值。</param>
        /// <param name="name">name 屬性的初始值。</param>
        /// <param name="cid">cid 屬性的初始值。</param>
        /// <param name="price">price 屬性的初始值。</param>
        /// <param name="instock">instock 屬性的初始值。</param>
        public static product Createproduct(global::System.Int32 id, global::System.String name, global::System.Int32 cid, global::System.Decimal price, global::System.Int32 instock)
        {
            product product = new product();
            product.id = id;
            product.name = name;
            product.cid = cid;
            product.price = price;
            product.instock = instock;
            return product;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cid
        {
            get
            {
                return _cid;
            }
            set
            {
                OncidChanging(value);
                ReportPropertyChanging("cid");
                _cid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cid");
                OncidChanged();
            }
        }
        private global::System.Int32 _cid;
        partial void OncidChanging(global::System.Int32 value);
        partial void OncidChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String image
        {
            get
            {
                return _image;
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.String _image;
        partial void OnimageChanging(global::System.String value);
        partial void OnimageChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 instock
        {
            get
            {
                return _instock;
            }
            set
            {
                OninstockChanging(value);
                ReportPropertyChanging("instock");
                _instock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("instock");
                OninstockChanged();
            }
        }
        private global::System.Int32 _instock;
        partial void OninstockChanging(global::System.Int32 value);
        partial void OninstockChanged();

        #endregion
    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pcsysModel", "FK_product_catogory", "catogory")]
        public catogory catogory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catogory>("pcsysModel.FK_product_catogory", "catogory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catogory>("pcsysModel.FK_product_catogory", "catogory").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<catogory> catogoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catogory>("pcsysModel.FK_product_catogory", "catogory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<catogory>("pcsysModel.FK_product_catogory", "catogory", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcsysModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 sysdiagrams 物件。
        /// </summary>
        /// <param name="name">name 屬性的初始值。</param>
        /// <param name="principal_id">principal_id 屬性的初始值。</param>
        /// <param name="diagram_id">diagram_id 屬性的初始值。</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
